# Generated by Django 2.2 on 2020-02-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=20, verbose_name='名称')),
                ('bpub_date', models.DateField(null=True, verbose_name='发布日期')),
                ('bread', models.IntegerField(default=0, verbose_name='阅读量')),
                ('bcomment', models.IntegerField(default=0, verbose_name='评论量')),
                ('image', models.CharField(max_length=300, null=True, verbose_name='图片')),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
        migrations.CreateModel(
            name='HeroInfoSerializer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hname', models.CharField(max_length=20)),
                ('hgender', models.IntegerField(choices=[(0, 'male'), (1, 'female')], default=0)),
                ('hcomment', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'hero',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(db_column='password_hash', max_length=128)),
            ],
            options={
                'db_table': 'bbs_user',
            },
        ),
    ]
