"""empty message

Revision ID: 7bfb1973e502
Revises: 09b6d414b172
Create Date: 2019-07-27 14:45:23.936921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bfb1973e502'
down_revision = '09b6d414b172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('cno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cname', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('cno')
    )
    op.create_table('sc',
    sa.Column('sno', sa.Integer(), nullable=True),
    sa.Column('cno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cno'], ['course.cno'], ),
    sa.ForeignKeyConstraint(['sno'], ['student.sno'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sc')
    op.drop_table('course')
    # ### end Alembic commands ###
