"""empty message

Revision ID: a9f7118f2f52
Revises: c34f4cfb3293
Create Date: 2019-07-27 14:09:00.073932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9f7118f2f52'
down_revision = 'c34f4cfb3293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('sno', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sname', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('sno')
    )
    op.create_table('detail',
    sa.Column('did', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nickyname', sa.String(length=60), nullable=True),
    sa.Column('sno', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sno'], ['student.sno'], ),
    sa.PrimaryKeyConstraint('did')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detail')
    op.drop_table('student')
    # ### end Alembic commands ###
