"""empty message

Revision ID: c34f4cfb3293
Revises: 4ddfc1ac98bf
Create Date: 2019-07-27 11:05:40.906228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c34f4cfb3293'
down_revision = '4ddfc1ac98bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbs_posts',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=20000), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('istop', sa.Boolean(), nullable=True),
    sa.Column('islight', sa.Boolean(), nullable=True),
    sa.Column('iselite', sa.Boolean(), nullable=True),
    sa.Column('isdel', sa.Boolean(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('replycount', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['bbs_category.cid'], ),
    sa.ForeignKeyConstraint(['uid'], ['bbs_user.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('content', mysql.VARCHAR(length=20000), nullable=True),
    sa.Column('addtime', mysql.DATETIME(), nullable=True),
    sa.Column('istop', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('islight', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('iselite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('isdel', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('hits', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('replycount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['bbs_category.cid'], name='posts_ibfk_1'),
    sa.ForeignKeyConstraint(['uid'], ['bbs_user.uid'], name='posts_ibfk_2'),
    sa.PrimaryKeyConstraint('pid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('bbs_posts')
    # ### end Alembic commands ###
