"""empty message

Revision ID: 09b6d414b172
Revises: a9f7118f2f52
Create Date: 2019-07-27 14:26:51.209376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09b6d414b172'
down_revision = 'a9f7118f2f52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'detail', ['sno'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detail', type_='unique')
    # ### end Alembic commands ###
