"""empty message

Revision ID: 2e4a6450dd74
Revises: 
Create Date: 2019-07-27 09:45:18.394256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4a6450dd74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbs_category',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryname', sa.String(length=100), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('themenum', sa.Integer(), nullable=True),
    sa.Column('replynum', sa.Integer(), nullable=True),
    sa.Column('lastpost', sa.String(length=200), nullable=True),
    sa.Column('compere', sa.String(length=20), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('categoryname')
    )
    op.create_table('bbs_user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('realname', sa.String(length=60), nullable=True),
    sa.Column('portrait', sa.String(length=200), nullable=True),
    sa.Column('regtime', sa.DATETIME(), nullable=True),
    sa.Column('qq', sa.String(length=15), nullable=True),
    sa.Column('signature', sa.String(length=300), nullable=True),
    sa.Column('answer', sa.String(length=300), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bbs_user')
    op.drop_table('bbs_category')
    # ### end Alembic commands ###
