"""empty message

Revision ID: 4ddfc1ac98bf
Revises: f5e8cc2ce202
Create Date: 2019-07-27 11:04:39.506139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ddfc1ac98bf'
down_revision = 'f5e8cc2ce202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbs_category',
    sa.Column('cid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('categoryname', sa.String(length=100), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('themenum', sa.Integer(), nullable=True),
    sa.Column('replynum', sa.Integer(), nullable=True),
    sa.Column('lastpost', sa.String(length=200), nullable=True),
    sa.Column('compere', sa.String(length=20), nullable=True),
    sa.Column('startdate', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    sa.UniqueConstraint('categoryname')
    )
    op.create_table('bbs_user',
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('realname', sa.String(length=60), nullable=True),
    sa.Column('portrait', sa.String(length=200), nullable=True),
    sa.Column('regtime', sa.DATETIME(), nullable=True),
    sa.Column('qq', sa.String(length=15), nullable=True),
    sa.Column('signature', sa.String(length=300), nullable=True),
    sa.Column('answer', sa.String(length=300), nullable=True),
    sa.Column('isactive', sa.Boolean(), nullable=True),
    sa.Column('email', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('pid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.String(length=20000), nullable=True),
    sa.Column('addtime', sa.DateTime(), nullable=True),
    sa.Column('istop', sa.Boolean(), nullable=True),
    sa.Column('islight', sa.Boolean(), nullable=True),
    sa.Column('iselite', sa.Boolean(), nullable=True),
    sa.Column('isdel', sa.Boolean(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('replycount', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('cid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cid'], ['bbs_category.cid'], ),
    sa.ForeignKeyConstraint(['uid'], ['bbs_user.uid'], ),
    sa.PrimaryKeyConstraint('pid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('bbs_user')
    op.drop_table('bbs_category')
    # ### end Alembic commands ###
