"""empty message

Revision ID: f5e8cc2ce202
Revises: 2e4a6450dd74
Create Date: 2019-07-27 11:03:59.427445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5e8cc2ce202'
down_revision = '2e4a6450dd74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grade')
    op.drop_table('student')
    op.drop_index('username', table_name='bbs_user')
    op.drop_table('bbs_user')
    op.drop_table('course')
    op.drop_index('categoryname', table_name='bbs_category')
    op.drop_table('bbs_category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bbs_category',
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('categoryname', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('themenum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('replynum', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('lastpost', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('compere', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('startdate', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('categoryname', 'bbs_category', ['categoryname'], unique=True)
    op.create_table('course',
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('cname', mysql.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('cid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('bbs_user',
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('sex', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('birthday', sa.DATE(), nullable=True),
    sa.Column('realname', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('portrait', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('regtime', mysql.DATETIME(), nullable=True),
    sa.Column('qq', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('signature', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('answer', mysql.VARCHAR(length=300), nullable=True),
    sa.Column('isactive', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=300), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'bbs_user', ['username'], unique=True)
    op.create_table('student',
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sname', mysql.VARCHAR(length=20), nullable=True),
    sa.PrimaryKeyConstraint('sid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('grade',
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('score', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['sid'], ['student.sid'], name='fk_student_sid', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sid', 'cid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
