# Generated by Django 2.2.9 on 2020-01-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('classname', models.CharField(blank=True, max_length=60, null=True)),
                ('parentid', models.IntegerField()),
                ('replycount', models.SmallIntegerField(blank=True, null=True)),
                ('forumcount', models.SmallIntegerField(blank=True, null=True)),
                ('compere', models.CharField(blank=True, max_length=20, null=True)),
                ('classpic', models.CharField(blank=True, max_length=200, null=True)),
                ('descrition', models.CharField(blank=True, max_length=200, null=True)),
                ('orderby', models.SmallIntegerField(blank=True, null=True)),
                ('lastpost', models.CharField(blank=True, max_length=3000, null=True)),
                ('ispass', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbs_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Closeip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.IntegerField()),
                ('addtime', models.IntegerField()),
                ('overtime', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbs_closeip',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('lid', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('displayorder', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('addtime', models.IntegerField()),
            ],
            options={
                'db_table': 'bbs_link',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('tid', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('addtime', models.IntegerField()),
                ('ispay', models.IntegerField()),
            ],
            options={
                'db_table': 'bbs_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(blank=True, null=True)),
                ('authorid', models.IntegerField()),
                ('title', models.CharField(max_length=600)),
                ('content', models.TextField()),
                ('addtime', models.IntegerField()),
                ('addip', models.IntegerField()),
                ('classid', models.IntegerField()),
                ('replycount', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('istop', models.IntegerField()),
                ('elite', models.IntegerField()),
                ('ishot', models.IntegerField()),
                ('rate', models.SmallIntegerField()),
                ('attachment', models.SmallIntegerField(blank=True, null=True)),
                ('isdel', models.IntegerField()),
                ('style', models.CharField(blank=True, max_length=10, null=True)),
                ('isdisplay', models.IntegerField()),
            ],
            options={
                'db_table': 'bbs_post',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tid', models.IntegerField(blank=True, null=True)),
                ('authorid', models.IntegerField()),
                ('content', models.TextField()),
                ('addtime', models.IntegerField()),
                ('addip', models.IntegerField()),
                ('classid', models.IntegerField()),
                ('isdel', models.IntegerField()),
                ('isdisplay', models.IntegerField()),
            ],
            options={
                'db_table': 'bbs_reply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('usertype', models.IntegerField(blank=True, null=True)),
                ('sex', models.IntegerField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('realname', models.CharField(blank=True, max_length=60, null=True)),
                ('portrait', models.CharField(blank=True, max_length=200, null=True)),
                ('regtime', models.DateTimeField(blank=True, null=True)),
                ('qq', models.CharField(blank=True, max_length=15, null=True)),
                ('signature', models.CharField(blank=True, max_length=300, null=True)),
                ('answer', models.CharField(blank=True, max_length=300, null=True)),
                ('isactive', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('lasttime', models.DateTimeField(blank=True, null=True)),
                ('allowlogin', models.IntegerField(blank=True, null=True)),
                ('grade', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bbs_user',
                'managed': False,
            },
        ),
    ]
