# Generated by Django 2.2 on 2020-02-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=200)),
                ('bpub_date', models.DateField(auto_now_add=True, null=True)),
                ('bread', models.IntegerField(default=0)),
                ('bcomment', models.IntegerField(default=0)),
                ('bimage', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'bookinfo',
            },
        ),
    ]
